### ISSUE TITLE
Replace EventMachine/faye-websocket with websocket-driver for ARI WebSocket

### ISSUE THREAD

**Issue by emilianodellacasa** [emilianodellacasa/ruby-asterisk#82]
## Problem

The `ruby head` CI job fails during `bundle install`: `eventmachine` 1.2.7 does not compile on ruby-head (4.1.0-dev) because the C API macros `Data_Wrap_Struct` / `Data_Get_Struct` have been removed:

```
rubymain.cpp:53:19: error: 'Data_Wrap_Struct' was not declared in this scope
An error occurred while installing eventmachine (1.2.7), and Bundler cannot continue.
```

Dependency chain: `ruby-asterisk → faye-websocket 0.12.0 → eventmachine 1.2.7`. EventMachine's last release is from 2018 and the project is effectively unmaintained, so this will become a hard blocker when Ruby 4.1 ships.

## Solution

Replace the ARI WebSocket I/O layer: drop `faye-websocket` + `eventmachine`, use **`websocket-driver`** (pure Ruby, actively maintained, used by ActionCable) directly over a plain `TCPSocket` (+ `OpenSSL::SSL::SSLSocket` for `wss`), with plain OS threads for the read loop, ping keep-alive and reconnect — mirroring the Thread-based design adopted for the AMI Reactor in #79.

Since `faye-websocket` is itself a thin EventMachine wrapper around `websocket-driver`, the wire protocol and handshake remain identical; only the I/O layer changes.

Public API of `RubyAsterisk::ARI::WebSocket` stays unchanged: `connect`, `on`, `disconnect`, `connected?`, `send_message?`, same options (`logger`, `ping_interval`, `auto_reconnect`, `reconnect_delay`).

**Comment by emilianodellacasa** [comment]
Done
